version: '3.10'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  database:
    container_name: db_user
    image: docker.io/postgres:15
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PORT: 5432
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  milvus:
    container_name: milvus
    image: milvusdb/milvus:2.3.1
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      MILVUS_LOG_LEVEL: debug

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
      - milvus
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/rag
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530

volumes:
  db_data:
